<?php
include("ConnexionBDD.php");
session_start();



?>
<!DOCTYPE HTML>

<html>
<head>
<meta charset="UTF-8" />
<title> Utilisateurs </title>
<link rel="stylesheet" media="screen" href="carte.css">
</head>
<body> 
<?php
include("barre_menu.php");
?>
    <form method="GET" action="recherche.php"> 
     Rechercher un mot : <input type="text" name="query">
     <input type="SUBMIT" value="Rechercher"> 
     </form>

    <center>
    <h1> <center>Carte intéractive des équipes qualifiées en playoffs de la NBA :</center></h1>
<tbody><tr>
<td width="250px" rowspan="4"><table  style="width:auto; margin:0; border:none; border-spacing:0; padding:0; text-align:center;">
<tbody><tr><td style="border:none; padding:0"><div style="position:relative;;"><img src="//upload.wikimedia.org/wikipedia/commons/thumb/0/03/Usa_edcp_%28%2BHI_%2BAK%29_location_map.svg/600px-Usa_edcp_%28%2BHI_%2BAK%29_location_map.svg.png" decoding="async" width="600" height="371" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/03/Usa_edcp_%28%2BHI_%2BAK%29_location_map.svg/900px-Usa_edcp_%28%2BHI_%2BAK%29_location_map.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/03/Usa_edcp_%28%2BHI_%2BAK%29_location_map.svg/1200px-Usa_edcp_%28%2BHI_%2BAK%29_location_map.svg.png 2x" data-file-width="1181" data-file-height="731" /></a>
<div style="position:absolute;top:63.719917694136%;left:21.156812616859%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left: 0.5em;text-align:left;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Phoenix" title="Suns de Phoenix">Phoenix</a></b></span></div></div></div>
<div style="position:absolute;top:90.56877679549%;left:81.08873205974%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left:-12.6em;text-align:right;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Miami" title="Heat de Miami">Miami</a></b></span></div></div></div>
<div style="position:absolute;top:61.292765070039%;left:60.634497374396%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left:-12.6em;text-align:right;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Memphis" title="Grizzlies de Memphis">Memphis</a></b></span></div></div></div>
<div style="position:absolute;top:69.997495604458%;left:48.550948123866%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left:-12.6em;text-align:right;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte" href="equipe.php?nomEquipe=Dallas" title="Mavericks de Dallas">Dallas</a></b></span></div></div></div>
<div style="position:absolute;top:33.214760679381%;left:62.787108068245%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left:-12.6em;text-align:right;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Milwaukee" title="Bucks de Milwaukee">Milwaukee</a></b></span></div></div></div>
<div style="position:absolute;top:29.869330189713%;left:89.756806693093%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-1.75em;left: -6em;text-align:center;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Boston" title="Celtics de Boston">Boston</a></b></span></div></div></div>
<div style="position:absolute;top:38.845898736532%;left:84.212302498974%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top: 0.00em;left: 0.6em;text-align:left;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Philadelphie" title="76ers de Philadelphie">Philadelphie</a></b></span></div></div></div>
<div style="position:absolute;top:42.550979709184%;left:5.8304045175601%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left: 0.5em;text-align:left;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Golden" title="Warriors de Golden State">Golden State</a></b></span></div></div></div>
<div style="position:absolute;top:38.589198982217%;left:24.108726205448%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-1.75em;left: -6em;text-align:center;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Utah" title="Jazz de l&#39;Utah">Utah</a></b></span></div></div></div>
<div style="position:absolute;top:37.148356711127%;left:63.434651293968%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left: 0.5em;text-align:left;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Chicago" title="Bulls de Chicago">Chicago</a></b></span></div></div></div>
<div style="position:absolute;top:28.300391117708%;left:75.974696932935%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-1.75em;left: -6em;text-align:center;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Toronto" title="Raptors de Toronto">Toronto</a></b></span></div></div></div>
<div style="position:absolute;top:45.80088330522%;left:35.693217669219%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left: 0.5em;text-align:left;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Denver" title="Nuggets de Denver">Denver</a></b></span></div></div></div>
<div style="position:absolute;top:64.556929400136%;left:70.804814071608%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left: 0.5em;text-align:left;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Atlanta" title="Hawks d&#39;Atlanta">Atlanta</a></b></span></div></div></div>
<div style="position:absolute;top:79.424249544845%;left:62.026922634514%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-1.75em;left: -6em;text-align:center;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Orleans" title="Pelicans de La Nouvelle-Orléans">La Nouvelle-Orléans</a></b></span></div></div></div>
<div style="position:absolute;top:35.647436621582%;left:85.822299939993%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-0.80em;left: 0.5em;text-align:left;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Brooklyn" title="Nets de Brooklyn">Brooklyn</a></b></span></div></div></div>
<div style="position:absolute;top:28.585721604499%;left:54.401099954019%;width:0px;height:0px;margin:0;padding:0;line-height:0px;background-color:transparent;"><div style="position:relative;top:-8px;left:-8px;width:16px;height:16px;background-color:transparent;"><img alt="Localisation de la ville" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/16px-City_locator_3.svg.png" decoding="async" width="16" height="16" class="noviewer" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/24px-City_locator_3.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/f0/City_locator_3.svg/32px-City_locator_3.svg.png 2x" data-file-width="16" data-file-height="16" /></div><div style="position:relative;top:-17px;"><div style="font-size:100%;position:relative;top:-1.75em;left: -6em;text-align:center;width:12em;line-height:1.2em;"><span class="toponyme"><b><a class="carte"href="equipe.php?nomEquipe=Minnesota" title="Timberwolves du Minnesota">Minneapolis</a></b></span></div></div></div>
</div></td></tr></tbody></table>
</td></tr></tbody>
</center>
</body>

</html>

