<div class="tournament">
      <?php
   
      echo"<table>";
      echo"<tr>";
      echo"<td><div class=formtext>".htmlspecialchars($row['nomEquipe'])."</div></td>"; 
      echo"<td></td><td></td><td></td><td></td><td></td>";
      echo"<td><div  class=formtext>".htmlspecialchars($row['AbrevEquipe'])."</div></td>";
      echo"</tr>";
      echo"<tr>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext2>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td></td>";
      echo"<td></td>";
      echo"<td></td>";
      echo"<td><div class=formtext2>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"</tr>";
      echo"<tr>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext2>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext3>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td></td>";
      echo"<td><div class=formtext3>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext2>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"</tr>";
      echo"<tr>";
      echo"<td><div class=formtext2>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td></td><td></td><td></td><td></td><td></td>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"</tr>";
      echo"<tr>";
      echo"<td></td><td></td><td></td>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td></td><td></td><td></td>";
      echo"</tr>";
      echo"<tr>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td></td><td></td><td></td><td></td><td></td>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"</tr>";
      echo"<tr>";
      echo"<td><div  class=formtext>".htmlspecialchars($row['AbrevEquipe'])."</div></td>";
      echo"<td><div class=formtext2>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext3>".htmlspecialchars($row['AbrevEquipe'])." </div></td>"; 
      echo"<td></td>";
      echo"<td><div class=formtext3>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext2>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div  class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"</tr>";
      echo"<tr>";
      echo"<td><div  class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext2>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td></td><td></td><td></td>";
      echo"<td><div class=formtext2>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"</tr>";
      echo"<tr>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"<td></td><td></td><td></td>";
      echo"<td></td><td></td>";
      echo"<td><div class=formtext>".htmlspecialchars($row['AbrevEquipe'])." </div></td>";
      echo"</tr>";
      echo"</table>";  
      
    ?>